name: alphabetalternative
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  assets_audio_player: ^3.1.1
  audioplayers: ^5.1.0
  card_stack_widget: ^0.1.5
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  url_launcher: ^6.1.14
  waterfall_flow: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: Bauhaus
      fonts:
        - asset: fonts/Muli-Bold.ttf
          weight: 700
    - family: Mooli  
      fonts:
        - asset: fonts/Mooli-Regular.ttf  
          weight: 700  
  assets:
    - assets/audio/
    - assets/words/
    - assets/GameRulesLogo.svg
    - assets/logo.svg
    - assets/rule.png
  uses-material-design: true