class CardDeckData {
  final List<String> frontCard = [
    'assets/words/A.svg',
    'assets/words/B.svg',
    'assets/words/C.svg',
    'assets/words/D.svg',
    'assets/words/E.svg',
    'assets/words/F.svg',
    'assets/words/G.svg',
    'assets/words/H.svg',
    'assets/words/I.svg',
    'assets/words/J.svg',
    'assets/words/K.svg',
    'assets/words/L.svg',
    'assets/words/M.svg',
    'assets/words/N.svg',
    'assets/words/O.svg',
    'assets/words/P.svg',
    'assets/words/Q.svg',
    'assets/words/R.svg',
    'assets/words/S.svg',
    'assets/words/T.svg',
    'assets/words/U.svg',
    'assets/words/V.svg',
    'assets/words/W.svg',
    'assets/words/X.svg',
    'assets/words/Y.svg',
    'assets/words/Z.svg',
  ];

  final List<String> backCard = [
    'assets/words/A word.svg',
    'assets/words/B word.svg',
    'assets/words/C word.svg',
    'assets/words/D word.svg',
    'assets/words/E word.svg',
    'assets/words/F word.svg',
    'assets/words/G word.svg',
    'assets/words/H word.svg',
    'assets/words/I word.svg',
    'assets/words/J word.svg',
    'assets/words/K word.svg',
    'assets/words/L word.svg',
    'assets/words/M word.svg',
    'assets/words/N word.svg',
    'assets/words/O word.svg',
    'assets/words/P word.svg',
    'assets/words/Q word.svg',
    'assets/words/R word.svg',
    'assets/words/S word.svg',
    'assets/words/T word.svg',
    'assets/words/U word.svg',
    'assets/words/V word.svg',
    'assets/words/W word.svg',
    'assets/words/X word.svg',
    'assets/words/Y word.svg',
    'assets/words/Z word.svg',
  ];
}
